-- WebPortfolioZumo — Supabase schema
-- Run with `npm run db:setup` or paste into Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique check (char_length(username) between 3 and 50),
  role text not null default 'user' check (role in ('user', 'admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 150),
  description text not null default '',
  images jsonb not null default '[]'::jsonb check (jsonb_typeof(images) = 'array'),
  tags text[] not null default array['งานในโรงเรียน']::text[],
  links jsonb not null default '{}'::jsonb check (jsonb_typeof(links) = 'object'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 80),
  email text not null check (char_length(email) between 3 and 254),
  subject text not null check (char_length(subject) between 1 and 120),
  message text not null check (char_length(message) between 1 and 2000),
  read boolean not null default false,
  created_at timestamptz not null default now()
);

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists(select 1 from public.profiles where id = auth.uid() and role = 'admin');
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  clean_username text;
  initial_role text;
begin
  clean_username := coalesce(nullif(trim(new.raw_user_meta_data->>'username'), ''), split_part(new.email, '@', 1), 'user');
  clean_username := left(clean_username, 42) || case when exists(select 1 from public.profiles where username = left(clean_username, 42)) then '_' || substr(new.id::text, 1, 7) else '' end;
  select case when exists(select 1 from public.profiles) then 'user' else 'admin' end into initial_role;
  insert into public.profiles(id, username, role) values(new.id, clean_username, initial_role);
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.projects enable row level security;
alter table public.contact_messages enable row level security;

drop policy if exists "Profiles can read self and admins can read all" on public.profiles;
create policy "Profiles can read self and admins can read all" on public.profiles for select using (id = auth.uid() or public.is_admin());
drop policy if exists "Users update own profile" on public.profiles;
create policy "Users update own profile" on public.profiles for update using (id = auth.uid()) with check (id = auth.uid());

drop policy if exists "Projects are public" on public.projects;
create policy "Projects are public" on public.projects for select using (true);
drop policy if exists "Admins create projects" on public.projects;
create policy "Admins create projects" on public.projects for insert with check (public.is_admin());
drop policy if exists "Admins update projects" on public.projects;
create policy "Admins update projects" on public.projects for update using (public.is_admin()) with check (public.is_admin());
drop policy if exists "Admins delete projects" on public.projects;
create policy "Admins delete projects" on public.projects for delete using (public.is_admin());

drop policy if exists "Anyone sends contact messages" on public.contact_messages;
create policy "Anyone sends contact messages" on public.contact_messages for insert to anon, authenticated with check (true);
drop policy if exists "Admins read messages" on public.contact_messages;
create policy "Admins read messages" on public.contact_messages for select using (public.is_admin());
drop policy if exists "Admins update messages" on public.contact_messages;
create policy "Admins update messages" on public.contact_messages for update using (public.is_admin()) with check (public.is_admin());
drop policy if exists "Admins delete messages" on public.contact_messages;
create policy "Admins delete messages" on public.contact_messages for delete using (public.is_admin());

revoke update on public.profiles from anon, authenticated;
grant select on public.profiles to authenticated;
grant update(username) on public.profiles to authenticated;
grant select on public.projects to anon, authenticated;
grant insert, update, delete on public.projects to authenticated;
grant usage, select on sequence public.projects_id_seq to authenticated;
grant insert on public.contact_messages to anon, authenticated;
grant select, update, delete on public.contact_messages to authenticated;
grant usage, select on sequence public.contact_messages_id_seq to anon, authenticated;

insert into storage.buckets(id, name, public, file_size_limit, allowed_mime_types)
values ('project-images', 'project-images', true, 20971520, array['image/jpeg','image/png','image/gif','image/webp'])
on conflict (id) do update set public = excluded.public, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Public reads project images" on storage.objects;
create policy "Public reads project images" on storage.objects for select using (bucket_id = 'project-images');
drop policy if exists "Admins upload project images" on storage.objects;
create policy "Admins upload project images" on storage.objects for insert to authenticated with check (bucket_id = 'project-images' and public.is_admin());
drop policy if exists "Admins update project images" on storage.objects;
create policy "Admins update project images" on storage.objects for update to authenticated using (bucket_id = 'project-images' and public.is_admin());
drop policy if exists "Admins delete project images" on storage.objects;
create policy "Admins delete project images" on storage.objects for delete to authenticated using (bucket_id = 'project-images' and public.is_admin());

insert into public.projects(name, description, images, tags, links)
select 'Smart Farm IoT System', 'ระบบรดน้ำต้นไม้อัตโนมัติ ใช้ Sensor วัดความชื้นร่วมกับ ESP32 และแสดงผลแบบ Real-time บน Blynk', '["/assets/bg_bridge.png"]'::jsonb, array['งานในโรงเรียน'], '{}'::jsonb
where not exists (select 1 from public.projects);

insert into public.projects(name, description, images, tags, links)
select 'AI Object Detection', 'ฝึกโมเดลตรวจจับวัตถุด้วย Python, OpenCV และชุดข้อมูลที่สร้างขึ้นเอง', '["/assets/Python-logo-notext.svg.png"]'::jsonb, array['เข้าร่วมกิจกรรม'], '{}'::jsonb
where (select count(*) from public.projects) = 1;
