-- WebPortfolioZumo — Supabase schema
-- Run with `npm run db:setup` or paste into Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique check (char_length(username) between 3 and 50),
  role text not null default 'user' check (role in ('user', 'admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 150),
  description text not null default '',
  images jsonb not null default '[]'::jsonb check (jsonb_typeof(images) = 'array'),
  tags text[] not null default array['งานในโรงเรียน']::text[],
  links jsonb not null default '{}'::jsonb check (jsonb_typeof(links) = 'object'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 80),
  email text not null check (char_length(email) between 3 and 254),
  subject text not null check (char_length(subject) between 1 and 120),
  message text not null check (char_length(message) between 1 and 2000),
  read boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.admin_activity (
  id bigint generated by default as identity primary key,
  actor_id uuid references auth.users(id) on delete set null,
  action text not null,
  entity_type text not null,
  entity_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists(select 1 from public.profiles where id = auth.uid() and role = 'admin');
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  clean_username text;
begin
  clean_username := coalesce(nullif(trim(new.raw_user_meta_data->>'username'), ''), split_part(new.email, '@', 1), 'user');
  clean_username := left(clean_username, 42) || case when exists(select 1 from public.profiles where username = left(clean_username, 42)) then '_' || substr(new.id::text, 1, 7) else '' end;
  insert into public.profiles(id, username, role) values(new.id, clean_username, 'user');
  return new;
end;
$$;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists projects_set_updated_at on public.projects;
create trigger projects_set_updated_at before update on public.projects for each row execute procedure public.set_updated_at();

create or replace function public.audit_admin_change()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  row_data jsonb;
begin
  if not public.is_admin() then
    if tg_op = 'DELETE' then return old; else return new; end if;
  end if;

  row_data := case when tg_op = 'DELETE' then to_jsonb(old) else to_jsonb(new) end;
  insert into public.admin_activity(actor_id, action, entity_type, entity_id, details)
  values (
    auth.uid(),
    tg_op,
    tg_table_name,
    row_data->>'id',
    jsonb_strip_nulls(jsonb_build_object('name', row_data->>'name', 'subject', row_data->>'subject', 'username', row_data->>'username'))
  );

  if tg_op = 'DELETE' then return old; else return new; end if;
end;
$$;

drop trigger if exists audit_projects_changes on public.projects;
create trigger audit_projects_changes after insert or update or delete on public.projects for each row execute procedure public.audit_admin_change();
drop trigger if exists audit_messages_changes on public.contact_messages;
create trigger audit_messages_changes after update or delete on public.contact_messages for each row execute procedure public.audit_admin_change();
drop trigger if exists audit_profiles_changes on public.profiles;
create trigger audit_profiles_changes after update on public.profiles for each row execute procedure public.audit_admin_change();

create or replace function public.admin_delete_project(target_project_id bigint)
returns text[]
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  project_images jsonb;
  storage_paths text[];
begin
  if not public.is_admin() then
    raise exception 'Admin permission required' using errcode = '42501';
  end if;

  delete from public.projects where id = target_project_id returning images into project_images;
  if project_images is null then
    raise exception 'Project not found' using errcode = 'P0002';
  end if;

  select coalesce(array_agg(value), array[]::text[])
  into storage_paths
  from jsonb_array_elements_text(project_images) as value;
  return storage_paths;
end;
$$;

create or replace function public.admin_set_user_role(target_user_id uuid, next_role text)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if not public.is_admin() then
    raise exception 'Admin permission required' using errcode = '42501';
  end if;
  if next_role not in ('user', 'admin') then
    raise exception 'Invalid role' using errcode = '22023';
  end if;
  if target_user_id = auth.uid() then
    raise exception 'You cannot change your own role' using errcode = '42501';
  end if;
  if next_role = 'user'
     and (select role from public.profiles where id = target_user_id) = 'admin'
     and (select count(*) from public.profiles where role = 'admin') <= 1 then
    raise exception 'At least one admin is required' using errcode = '23514';
  end if;

  update public.profiles set role = next_role where id = target_user_id;
  if not found then
    raise exception 'User profile not found' using errcode = 'P0002';
  end if;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.projects enable row level security;
alter table public.contact_messages enable row level security;
alter table public.admin_activity enable row level security;

drop policy if exists "Profiles can read self and admins can read all" on public.profiles;
create policy "Profiles can read self and admins can read all" on public.profiles for select using (id = auth.uid() or public.is_admin());
drop policy if exists "Users update own profile" on public.profiles;
create policy "Users update own profile" on public.profiles for update using (id = auth.uid()) with check (id = auth.uid());

drop policy if exists "Projects are public" on public.projects;
create policy "Projects are public" on public.projects for select using (true);
drop policy if exists "Admins create projects" on public.projects;
create policy "Admins create projects" on public.projects for insert with check (public.is_admin());
drop policy if exists "Admins update projects" on public.projects;
create policy "Admins update projects" on public.projects for update using (public.is_admin()) with check (public.is_admin());
drop policy if exists "Admins delete projects" on public.projects;
create policy "Admins delete projects" on public.projects for delete using (public.is_admin());

drop policy if exists "Anyone sends contact messages" on public.contact_messages;
create policy "Anyone sends contact messages" on public.contact_messages for insert to anon, authenticated with check (true);
drop policy if exists "Admins read messages" on public.contact_messages;
create policy "Admins read messages" on public.contact_messages for select using (public.is_admin());
drop policy if exists "Admins update messages" on public.contact_messages;
create policy "Admins update messages" on public.contact_messages for update using (public.is_admin()) with check (public.is_admin());
drop policy if exists "Admins delete messages" on public.contact_messages;
create policy "Admins delete messages" on public.contact_messages for delete using (public.is_admin());

drop policy if exists "Admins read activity" on public.admin_activity;
create policy "Admins read activity" on public.admin_activity for select using (public.is_admin());

revoke all on public.profiles from anon;
revoke update on public.profiles from authenticated;
revoke insert, update, delete on public.projects from anon;
revoke select, update, delete on public.contact_messages from anon;
revoke all on public.admin_activity from anon, authenticated;
revoke all on function public.admin_delete_project(bigint) from public;
revoke all on function public.admin_set_user_role(uuid, text) from public;
grant select on public.profiles to authenticated;
grant update(username) on public.profiles to authenticated;
grant select on public.projects to anon, authenticated;
grant insert, update, delete on public.projects to authenticated;
grant usage, select on sequence public.projects_id_seq to authenticated;
grant insert on public.contact_messages to anon, authenticated;
grant select, update, delete on public.contact_messages to authenticated;
grant usage, select on sequence public.contact_messages_id_seq to anon, authenticated;
grant select on public.admin_activity to authenticated;
grant usage, select on sequence public.admin_activity_id_seq to authenticated;
grant execute on function public.admin_delete_project(bigint) to authenticated;
grant execute on function public.admin_set_user_role(uuid, text) to authenticated;

insert into storage.buckets(id, name, public, file_size_limit, allowed_mime_types)
values ('project-images', 'project-images', true, 20971520, array['image/jpeg','image/png','image/gif','image/webp'])
on conflict (id) do update set public = excluded.public, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Public reads project images" on storage.objects;
create policy "Public reads project images" on storage.objects for select using (bucket_id = 'project-images');
drop policy if exists "Admins upload project images" on storage.objects;
create policy "Admins upload project images" on storage.objects for insert to authenticated with check (bucket_id = 'project-images' and public.is_admin());
drop policy if exists "Admins update project images" on storage.objects;
create policy "Admins update project images" on storage.objects for update to authenticated using (bucket_id = 'project-images' and public.is_admin());
drop policy if exists "Admins delete project images" on storage.objects;
create policy "Admins delete project images" on storage.objects for delete to authenticated using (bucket_id = 'project-images' and public.is_admin());

insert into public.projects(name, description, images, tags, links)
select 'Smart Farm IoT System', 'ระบบรดน้ำต้นไม้อัตโนมัติ ใช้ Sensor วัดความชื้นร่วมกับ ESP32 และแสดงผลแบบ Real-time บน Blynk', '["/assets/bg_bridge.png"]'::jsonb, array['งานในโรงเรียน'], '{}'::jsonb
where not exists (select 1 from public.projects);

insert into public.projects(name, description, images, tags, links)
select 'AI Object Detection', 'ฝึกโมเดลตรวจจับวัตถุด้วย Python, OpenCV และชุดข้อมูลที่สร้างขึ้นเอง', '["/assets/Python-logo-notext.svg.png"]'::jsonb, array['เข้าร่วมกิจกรรม'], '{}'::jsonb
where (select count(*) from public.projects) = 1;
